### PR TITLE
Added semantic HTML and JS logic for the carousel to work. 

### PR DESCRIPTION
**Pull request by Diegopie**
Responsiveness with the carousel is not working when changing the screen size, page must be refreshed before the images display properly

### CODE REVIEW

**Comment by Feizhi255** [comment]
good to know

**Review by Feizhi255 — COMMENTED** [review]
good to know

**Comment by volosevych** [comment]
Looks good! 👍

**Review by volosevych — APPROVED** [review]
👍

**Review by ghost — APPROVED** [review]
Looks good! sorry took a bit to copy paste and look at it

**Pull request merged**
